FROM golang:1.20-alpine AS builder

WORKDIR /app

COPY api/ .

RUN go mod download

RUN go build -o main .

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/ ./

EXPOSE 8081

CMD "./main"
